// Generated by LiveScript 1.3.1
var start, isBlink, isLight, isRun, isShow, isWarned, handler, latency, stopBy, delay, audioRemind, audioEnd, wavePath, waveLevel, waveRaf, newAudio, soundToggle, formatTime, drawWave, updateWave, updateDisplay, show, adjust, toggle, reset, blink, count, run, resize;
start = null;
isBlink = false;
isLight = true;
isRun = false;
isShow = true;
isWarned = false;
handler = null;
latency = 0;
stopBy = null;
delay = 60000;
audioRemind = null;
audioEnd = null;
wavePath = null;
waveLevel = 0;
waveRaf = null;
newAudio = function(file){
  var x$, node;
  x$ = node = new Audio();
  x$.src = file;
  x$.loop = false;
  x$.load();
  document.body.appendChild(node);
  return node;
};
soundToggle = function(des, state){
  var x$;
  if (state) {
    return des.play();
  } else {
    x$ = des;
    x$.currentTime = 0;
    x$.pause();
    return x$;
  }
};
formatTime = function(ms){
  var remain, hours, minutes, seconds, milliseconds, pad2, pad3;
  remain = Math.max(0, Math.floor(ms));
  hours = Math.floor(remain / 3600000);
  minutes = Math.floor(remain / 60000) % 60;
  seconds = Math.floor(remain / 1000) % 60;
  milliseconds = remain % 1000;
  pad2 = function(v){
    if (v < 10) {
      return "0" + v;
    } else {
      return "" + v;
    }
  };
  pad3 = function(v){
    if (v < 10) {
      return "00" + v;
    } else if (v < 100) {
      return "0" + v;
    } else {
      return "" + v;
    }
  };
  return pad2(hours) + ":" + pad2(minutes) + ":" + pad2(seconds) + "." + pad3(milliseconds);
};
drawWave = function(){
  var width, height, base, amplitude, wavelength, offset, step, startX, prevX, prevY, path, i$, x$, waveY, ctrlX;
  if (!wavePath) {
    return;
  }
  width = window.innerWidth;
  height = window.innerHeight;
  base = Math.max(0, Math.min(height, height * waveLevel));
  amplitude = Math.max(12, Math.min(height * 0.08, 80));
  wavelength = Math.max(120, width / 6);
  offset = Date.now() / 600;
  step = wavelength / 2;
  startX = -wavelength;
  prevX = startX;
  prevY = base - Math.sin(prevX / wavelength * Math.PI * 2 + offset) * amplitude;
  path = "M0 " + height + " L" + startX + " " + height + " L" + prevX + " " + prevY;
  for (i$ = startX + step; i$ <= (x$ = width + wavelength); i$ += step) {
    waveY = base - Math.sin(i$ / wavelength * Math.PI * 2 + offset) * amplitude;
    ctrlX = prevX + step / 2;
    path += " C" + ctrlX + " " + prevY + ", " + ctrlX + " " + waveY + ", " + i$ + " " + waveY;
    prevX = i$;
    prevY = waveY;
  }
  path += " L" + (width + wavelength) + " " + height + " L0 " + height + " Z";
  wavePath.setAttribute('d', path);
  return waveRaf = requestAnimationFrame(drawWave);
};
updateWave = function(ms){
  var remain;
  if (!wavePath) {
    return;
  }
  remain = delay <= 0 ? 0 : Math.max(0, Math.min(ms, delay)) / delay;
  waveLevel = 1 - remain;
  if (!waveRaf) {
    return waveRaf = requestAnimationFrame(drawWave);
  }
};
updateDisplay = function(ms){
  $('#timer').text(formatTime(ms));
  updateWave(ms);
  return resize();
};
show = function(){
  isShow = !isShow;
  return $('.fbtn').css('opacity', isShow ? '1.0' : '0.1');
};
adjust = function(it, v){
  var current;
  if (isBlink) {
    return;
  }
  delay = delay + it * 1000;
  if (it === 0) {
    delay = v * 1000;
  }
  if (delay <= 0) {
    delay = 0;
  }
  current = start != null ? start.getTime() - new Date().getTime() + delay + latency : delay;
  return updateDisplay(current);
};
toggle = function(){
  isRun = !isRun;
  $('#toggle').text(isRun ? "STOP" : "RUN");
  if (!isRun && handler) {
    stopBy = new Date();
    clearInterval(handler);
    handler = null;
    soundToggle(audioEnd, false);
    soundToggle(audioRemind, false);
  }
  if (stopBy) {
    latency = latency + new Date().getTime() - stopBy.getTime();
  }
  if (isRun) {
    return run();
  }
};
reset = function(){
  if (delay === 0) {
    delay = 1000;
  }
  soundToggle(audioRemind, false);
  soundToggle(audioEnd, false);
  stopBy = 0;
  isWarned = false;
  isBlink = false;
  latency = 0;
  start = null;
  isRun = true;
  toggle();
  if (handler) {
    clearInterval(handler);
  }
  handler = null;
  $('#timer').css('color', '#fff');
  return updateDisplay(delay);
};
blink = function(){
  isBlink = true;
  isLight = !isLight;
  return $('#timer').css('color', isLight ? '#fff' : '#f00');
};
count = function(){
  var diff;
  diff = start.getTime() - new Date().getTime() + delay + latency;
  if (diff > 60000) {
    isWarned = false;
  }
  if (diff < 60000 && !isWarned) {
    isWarned = true;
    soundToggle(audioRemind, true);
  }
  if (diff < 55000) {
    soundToggle(audioRemind, false);
  }
  if (diff < 0 && !isBlink) {
    soundToggle(audioEnd, true);
    isBlink = true;
    diff = 0;
    clearInterval(handler);
    handler = setInterval(function(){
      return blink();
    }, 500);
  }
  return updateDisplay(diff);
};
run = function(){
  if (start === null) {
    start = new Date();
    latency = 0;
    isBlink = false;
  }
  if (handler) {
    clearInterval(handler);
  }
  if (isBlink) {
    return handler = setInterval(function(){
      return blink();
    }, 500);
  } else {
    return handler = setInterval(function(){
      return count();
    }, 100);
  }
};
resize = function(){
  var tm, w, h, len;
  tm = $('#timer');
  w = tm.width();
  h = $(window).height();
  len = tm.text().length;
  len >= 3 || (len = 3);
  tm.css('font-size', 1.2 * w / len + "px");
  return tm.css('line-height', h + "px");
};
window.onload = function(){
  wavePath = document.getElementById('wave-path');
  updateDisplay(delay);
  audioRemind = newAudio('audio/smb_warning.mp3');
  return audioEnd = newAudio('audio/smb_mariodie.mp3');
};
window.onresize = function(){
  resize();
  if (waveRaf) {
    cancelAnimationFrame(waveRaf);
  }
  return waveRaf = requestAnimationFrame(drawWave);
};